package com.afmvfcc.utils;

import com.afmvfcc.db.DatabaseConnection;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.util.logging.Logger;

/**
 * Generates data.js from the database and pushes it to:
 *   1. The local website folder (if configured), AND
 *   2. The GitHub repository (if configured).
 *
 * Both destinations are optional — whichever settings are present will be used.
 */
public class WebsiteExporter {

    private static final Logger LOG = Logger.getLogger(WebsiteExporter.class.getName());
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    // ----------------------------------------------------------------
    // Main export method — called after every save/delete
    // ----------------------------------------------------------------

    /**
     * @param localFolder  path to the local website folder (may be null / empty)
     */
    public static void exportAll(String localFolder) {
        try {
            String dataJs = buildDataJs();

            // 1. Write to local folder
            if (localFolder != null && !localFolder.isEmpty()) {
                File f = new File(localFolder, "data.js");
                try (PrintWriter w = new PrintWriter(new FileWriter(f))) {
                    w.print(dataJs);
                }
                LOG.info("data.js written to local folder: " + localFolder);
            }

            // 2. Push to GitHub
            String ghErr = GitHubSync.pushDataJs(dataJs);
            if (ghErr != null) {
                LOG.warning("GitHub push failed: " + ghErr);
            } else {
                LOG.info("data.js pushed to GitHub successfully.");
            }

        } catch (Exception e) {
            LOG.severe("WebsiteExporter.exportAll failed: " + e.getMessage());
            throw new RuntimeException(e);
        }
    }

    // ----------------------------------------------------------------
    // Build data.js content
    // ----------------------------------------------------------------

    public static String buildDataJs() throws SQLException {
        Connection conn = DatabaseConnection.getConnection();

        // ── Events ──
        List<Map<String, String>> events = new ArrayList<>();
        ResultSet evRs = conn.createStatement().executeQuery(
                "SELECT title, description, DATE_FORMAT(event_date,'%d %b %Y'), image_filename " +
                "FROM website_events WHERE event_date >= CURDATE() " +
                "ORDER BY event_date ASC LIMIT 20");
        while (evRs.next()) {
            Map<String, String> ev = new LinkedHashMap<>();
            ev.put("title", nvl(evRs.getString(1)));
            ev.put("desc",  nvl(evRs.getString(2)));
            ev.put("date",  nvl(evRs.getString(3)));
            // image_filename stored as GitHub Pages URL or local path
            String img = nvl(evRs.getString(4));
            ev.put("image", img);
            events.add(ev);
        }

        // ── Blogs ──
        List<Map<String, String>> blogs = new ArrayList<>();
        ResultSet blRs = conn.createStatement().executeQuery(
                "SELECT title, author, DATE_FORMAT(published_at,'%d %b %Y'), content " +
                "FROM website_blogs ORDER BY published_at DESC LIMIT 10");
        while (blRs.next()) {
            Map<String, String> bl = new LinkedHashMap<>();
            bl.put("title",   nvl(blRs.getString(1)));
            bl.put("author",  nvl(blRs.getString(2)));
            bl.put("date",    nvl(blRs.getString(3)));
            bl.put("content", nvl(blRs.getString(4)));
            blogs.add(bl);
        }

        // ── Serialise ──
        Map<String, Object> root = new LinkedHashMap<>();
        root.put("events", events);
        root.put("blogs",  blogs);

        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by AFM VFCC CMS — do not edit manually\n");
        sb.append("window.churchData = ");
        sb.append(GSON.toJson(root));
        sb.append(";\n");
        return sb.toString();
    }

    private static String nvl(String s) { return s != null ? s : ""; }
}
