# Increase Gradle JVM heap to fix "GC thrashing" / out of memory errors
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enable Gradle daemon for faster subsequent builds
org.gradle.daemon=true

# Enable parallel builds
org.gradle.parallel=true

# Enable configuration cache
org.gradle.caching=true

# Android specific
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
